 {{- $releaseName := .Release.Name -}}
{{- $chartName := include "extractable-management.name" . -}}
{{- if not .Values.user.useExternal -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.user.secretName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "extractable-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  users-json: {{ .Values.user.users | toJson | quote }}
{{- end }}
